/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_EsunnyTapApi_WRAP_H_
#define SWIG_EsunnyTapApi_WRAP_H_

class SwigDirector_ITapQuoteAPINotify : public ITapQuoteAPINotify, public Swig::Director {

public:
    SwigDirector_ITapQuoteAPINotify();
    virtual void OnRspLogin(TAPIINT32 errorCode,TapAPIQuotLoginRspInfo const *info);
    virtual void OnAPIReady();
    virtual void OnDisconnect(TAPIINT32 reasonCode);
    virtual void OnRspQryCommodity(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIQuoteCommodityInfo const *info);
    virtual void OnRspQryContract(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIQuoteContractInfo const *info);
    virtual void OnRspSubscribeQuote(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIQuoteWhole const *info);
    virtual void OnRspUnSubscribeQuote(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIContract const *info);
    virtual void OnRtnQuote(TapAPIQuoteWhole const *info);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnRspLogin, SWIG_Callback1_t callbackOnAPIReady, SWIG_Callback2_t callbackOnDisconnect, SWIG_Callback3_t callbackOnRspQryCommodity, SWIG_Callback4_t callbackOnRspQryContract, SWIG_Callback5_t callbackOnRspSubscribeQuote, SWIG_Callback6_t callbackOnRspUnSubscribeQuote, SWIG_Callback7_t callbackOnRtnQuote);

private:
    SWIG_Callback0_t swig_callbackOnRspLogin;
    SWIG_Callback1_t swig_callbackOnAPIReady;
    SWIG_Callback2_t swig_callbackOnDisconnect;
    SWIG_Callback3_t swig_callbackOnRspQryCommodity;
    SWIG_Callback4_t swig_callbackOnRspQryContract;
    SWIG_Callback5_t swig_callbackOnRspSubscribeQuote;
    SWIG_Callback6_t swig_callbackOnRspUnSubscribeQuote;
    SWIG_Callback7_t swig_callbackOnRtnQuote;
    void swig_init_callbacks();
};

class SwigDirector_ITapTradeAPINotify : public ITapTradeAPINotify, public Swig::Director {

public:
    SwigDirector_ITapTradeAPINotify();
    virtual void OnConnect();
    virtual void OnRspLogin(TAPIINT32 errorCode,TapAPITradeLoginRspInfo const *loginRspInfo);
    virtual void OnAPIReady();
    virtual void OnDisconnect(TAPIINT32 reasonCode);
    virtual void OnRspChangePassword(TAPIUINT32 sessionID,TAPIINT32 errorCode);
    virtual void OnRspSetReservedInfo(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPISTR_50 const info);
    virtual void OnRspQryAccount(TAPIUINT32 sessionID,TAPIUINT32 errorCode,TAPIYNFLAG isLast,TapAPIAccountInfo const *info);
    virtual void OnRspQryFund(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIFundData const *info);
    virtual void OnRtnFund(TapAPIFundData const *info);
    virtual void OnRspQryExchange(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIExchangeInfo const *info);
    virtual void OnRspQryCommodity(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPICommodityInfo const *info);
    virtual void OnRspQryContract(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPITradeContractInfo const *info);
    virtual void OnRtnContract(TapAPITradeContractInfo const *info);
    virtual void OnRtnOrder(TapAPIOrderInfoNotice const *info);
    virtual void OnRspOrderAction(TAPIUINT32 sessionID,TAPIUINT32 errorCode,TapAPIOrderActionRsp const *info);
    virtual void OnRspQryOrder(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIOrderInfo const *info);
    virtual void OnRspQryOrderProcess(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIOrderInfo const *info);
    virtual void OnRspQryFill(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIFillInfo const *info);
    virtual void OnRtnFill(TapAPIFillInfo const *info);
    virtual void OnRspQryPosition(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIPositionInfo const *info);
    virtual void OnRtnPosition(TapAPIPositionInfo const *info);
    virtual void OnRspQryClose(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPICloseInfo const *info);
    virtual void OnRtnClose(TapAPICloseInfo const *info);
    virtual void OnRtnPositionProfit(TapAPIPositionProfitNotice const *info);
    virtual void OnRspQryDeepQuote(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIDeepQuoteQryRsp const *info);
    virtual void OnRspQryExchangeStateInfo(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIExchangeStateInfo const *info);
    virtual void OnRtnExchangeStateInfo(TapAPIExchangeStateInfoNotice const *info);
    virtual void OnRtnReqQuoteNotice(TapAPIReqQuoteNotice const *info);
    virtual void OnRspUpperChannelInfo(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIUpperChannelInfo const *info);
    virtual void OnRspAccountRentInfo(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIAccountRentInfo const *info);
    virtual void OnRspSubmitUserLoginInfo(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPISubmitUserLoginRspInfo const *info);
    virtual void OnRspQryBill(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIBillQryRsp const *info);
    virtual void OnRspQryAccountStorage(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIAccountStorageInfo const *info);
    virtual void OnRtnAccountStorage(TapAPIAccountStorageInfo const *info);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(unsigned int, int, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(unsigned int, unsigned int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(unsigned int, unsigned int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback23_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback24_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback25_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback27_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback28_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback29_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback30_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback31_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback32_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback33_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnConnect, SWIG_Callback1_t callbackOnRspLogin, SWIG_Callback2_t callbackOnAPIReady, SWIG_Callback3_t callbackOnDisconnect, SWIG_Callback4_t callbackOnRspChangePassword, SWIG_Callback5_t callbackOnRspSetReservedInfo, SWIG_Callback6_t callbackOnRspQryAccount, SWIG_Callback7_t callbackOnRspQryFund, SWIG_Callback8_t callbackOnRtnFund, SWIG_Callback9_t callbackOnRspQryExchange, SWIG_Callback10_t callbackOnRspQryCommodity, SWIG_Callback11_t callbackOnRspQryContract, SWIG_Callback12_t callbackOnRtnContract, SWIG_Callback13_t callbackOnRtnOrder, SWIG_Callback14_t callbackOnRspOrderAction, SWIG_Callback15_t callbackOnRspQryOrder, SWIG_Callback16_t callbackOnRspQryOrderProcess, SWIG_Callback17_t callbackOnRspQryFill, SWIG_Callback18_t callbackOnRtnFill, SWIG_Callback19_t callbackOnRspQryPosition, SWIG_Callback20_t callbackOnRtnPosition, SWIG_Callback21_t callbackOnRspQryClose, SWIG_Callback22_t callbackOnRtnClose, SWIG_Callback23_t callbackOnRtnPositionProfit, SWIG_Callback24_t callbackOnRspQryDeepQuote, SWIG_Callback25_t callbackOnRspQryExchangeStateInfo, SWIG_Callback26_t callbackOnRtnExchangeStateInfo, SWIG_Callback27_t callbackOnRtnReqQuoteNotice, SWIG_Callback28_t callbackOnRspUpperChannelInfo, SWIG_Callback29_t callbackOnRspAccountRentInfo, SWIG_Callback30_t callbackOnRspSubmitUserLoginInfo, SWIG_Callback31_t callbackOnRspQryBill, SWIG_Callback32_t callbackOnRspQryAccountStorage, SWIG_Callback33_t callbackOnRtnAccountStorage);

private:
    SWIG_Callback0_t swig_callbackOnConnect;
    SWIG_Callback1_t swig_callbackOnRspLogin;
    SWIG_Callback2_t swig_callbackOnAPIReady;
    SWIG_Callback3_t swig_callbackOnDisconnect;
    SWIG_Callback4_t swig_callbackOnRspChangePassword;
    SWIG_Callback5_t swig_callbackOnRspSetReservedInfo;
    SWIG_Callback6_t swig_callbackOnRspQryAccount;
    SWIG_Callback7_t swig_callbackOnRspQryFund;
    SWIG_Callback8_t swig_callbackOnRtnFund;
    SWIG_Callback9_t swig_callbackOnRspQryExchange;
    SWIG_Callback10_t swig_callbackOnRspQryCommodity;
    SWIG_Callback11_t swig_callbackOnRspQryContract;
    SWIG_Callback12_t swig_callbackOnRtnContract;
    SWIG_Callback13_t swig_callbackOnRtnOrder;
    SWIG_Callback14_t swig_callbackOnRspOrderAction;
    SWIG_Callback15_t swig_callbackOnRspQryOrder;
    SWIG_Callback16_t swig_callbackOnRspQryOrderProcess;
    SWIG_Callback17_t swig_callbackOnRspQryFill;
    SWIG_Callback18_t swig_callbackOnRtnFill;
    SWIG_Callback19_t swig_callbackOnRspQryPosition;
    SWIG_Callback20_t swig_callbackOnRtnPosition;
    SWIG_Callback21_t swig_callbackOnRspQryClose;
    SWIG_Callback22_t swig_callbackOnRtnClose;
    SWIG_Callback23_t swig_callbackOnRtnPositionProfit;
    SWIG_Callback24_t swig_callbackOnRspQryDeepQuote;
    SWIG_Callback25_t swig_callbackOnRspQryExchangeStateInfo;
    SWIG_Callback26_t swig_callbackOnRtnExchangeStateInfo;
    SWIG_Callback27_t swig_callbackOnRtnReqQuoteNotice;
    SWIG_Callback28_t swig_callbackOnRspUpperChannelInfo;
    SWIG_Callback29_t swig_callbackOnRspAccountRentInfo;
    SWIG_Callback30_t swig_callbackOnRspSubmitUserLoginInfo;
    SWIG_Callback31_t swig_callbackOnRspQryBill;
    SWIG_Callback32_t swig_callbackOnRspQryAccountStorage;
    SWIG_Callback33_t swig_callbackOnRtnAccountStorage;
    void swig_init_callbacks();
};


#endif
