//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class ITapQuoteAPINotify : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ITapQuoteAPINotify(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ITapQuoteAPINotify obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ITapQuoteAPINotify obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ITapQuoteAPINotify() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_ITapQuoteAPINotify(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void OnRspLogin(int errorCode, TapAPIQuotLoginRspInfo info) {
    
  }

  public virtual void OnAPIReady() {
    
  }

  public virtual void OnDisconnect(int reasonCode) {
    
  }

  public virtual void OnRspQryCommodity(uint sessionID, int errorCode, char isLast, TapAPIQuoteCommodityInfo info) {
    
  }

  public virtual void OnRspQryContract(uint sessionID, int errorCode, char isLast, TapAPIQuoteContractInfo info) {
    
  }

  public virtual void OnRspSubscribeQuote(uint sessionID, int errorCode, char isLast, TapAPIQuoteWhole info) {
    
  }

  public virtual void OnRspUnSubscribeQuote(uint sessionID, int errorCode, char isLast, TapAPIContract info) {
    
  }

  public virtual void OnRtnQuote(TapAPIQuoteWhole info) {
    
  }

  public ITapQuoteAPINotify() : this(EsunnyTapApiPINVOKE.new_ITapQuoteAPINotify__SWIG_0(), true) {
    SwigDirectorConnect();
  }

  public ITapQuoteAPINotify(ITapQuoteAPINotify other) : this(EsunnyTapApiPINVOKE.new_ITapQuoteAPINotify__SWIG_1(ITapQuoteAPINotify.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    swigDelegate0 = (SwigDirectorMethodOnRspLogin);
    swigDelegate1 = (SwigDirectorMethodOnAPIReady);
    swigDelegate2 = (SwigDirectorMethodOnDisconnect);
    swigDelegate3 = (SwigDirectorMethodOnRspQryCommodity);
    swigDelegate4 = (SwigDirectorMethodOnRspQryContract);
    swigDelegate5 = (SwigDirectorMethodOnRspSubscribeQuote);
    swigDelegate6 = (SwigDirectorMethodOnRspUnSubscribeQuote);
    swigDelegate7 = (SwigDirectorMethodOnRtnQuote);
    EsunnyTapApiPINVOKE.ITapQuoteAPINotify_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7);
  }

  private void SwigDirectorMethodOnRspLogin(int errorCode, global::System.IntPtr info) {
    OnRspLogin(errorCode, (info == global::System.IntPtr.Zero) ? null : new TapAPIQuotLoginRspInfo(info, false));
  }

  private void SwigDirectorMethodOnAPIReady() {
    OnAPIReady();
  }

  private void SwigDirectorMethodOnDisconnect(int reasonCode) {
    OnDisconnect(reasonCode);
  }

  private void SwigDirectorMethodOnRspQryCommodity(uint sessionID, int errorCode, char isLast, global::System.IntPtr info) {
    OnRspQryCommodity(sessionID, errorCode, isLast, (info == global::System.IntPtr.Zero) ? null : new TapAPIQuoteCommodityInfo(info, false));
  }

  private void SwigDirectorMethodOnRspQryContract(uint sessionID, int errorCode, char isLast, global::System.IntPtr info) {
    OnRspQryContract(sessionID, errorCode, isLast, (info == global::System.IntPtr.Zero) ? null : new TapAPIQuoteContractInfo(info, false));
  }

  private void SwigDirectorMethodOnRspSubscribeQuote(uint sessionID, int errorCode, char isLast, global::System.IntPtr info) {
    OnRspSubscribeQuote(sessionID, errorCode, isLast, (info == global::System.IntPtr.Zero) ? null : new TapAPIQuoteWhole(info, false));
  }

  private void SwigDirectorMethodOnRspUnSubscribeQuote(uint sessionID, int errorCode, char isLast, global::System.IntPtr info) {
    OnRspUnSubscribeQuote(sessionID, errorCode, isLast, (info == global::System.IntPtr.Zero) ? null : new TapAPIContract(info, false));
  }

  private void SwigDirectorMethodOnRtnQuote(global::System.IntPtr info) {
    OnRtnQuote((info == global::System.IntPtr.Zero) ? null : new TapAPIQuoteWhole(info, false));
  }

  public delegate void SwigDelegateITapQuoteAPINotify_0(int errorCode, global::System.IntPtr info);
  public delegate void SwigDelegateITapQuoteAPINotify_1();
  public delegate void SwigDelegateITapQuoteAPINotify_2(int reasonCode);
  public delegate void SwigDelegateITapQuoteAPINotify_3(uint sessionID, int errorCode, char isLast, global::System.IntPtr info);
  public delegate void SwigDelegateITapQuoteAPINotify_4(uint sessionID, int errorCode, char isLast, global::System.IntPtr info);
  public delegate void SwigDelegateITapQuoteAPINotify_5(uint sessionID, int errorCode, char isLast, global::System.IntPtr info);
  public delegate void SwigDelegateITapQuoteAPINotify_6(uint sessionID, int errorCode, char isLast, global::System.IntPtr info);
  public delegate void SwigDelegateITapQuoteAPINotify_7(global::System.IntPtr info);

  private SwigDelegateITapQuoteAPINotify_0 swigDelegate0;
  private SwigDelegateITapQuoteAPINotify_1 swigDelegate1;
  private SwigDelegateITapQuoteAPINotify_2 swigDelegate2;
  private SwigDelegateITapQuoteAPINotify_3 swigDelegate3;
  private SwigDelegateITapQuoteAPINotify_4 swigDelegate4;
  private SwigDelegateITapQuoteAPINotify_5 swigDelegate5;
  private SwigDelegateITapQuoteAPINotify_6 swigDelegate6;
  private SwigDelegateITapQuoteAPINotify_7 swigDelegate7;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(int), typeof(TapAPIQuotLoginRspInfo) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(int) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(uint), typeof(int), typeof(char), typeof(TapAPIQuoteCommodityInfo) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(uint), typeof(int), typeof(char), typeof(TapAPIQuoteContractInfo) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(uint), typeof(int), typeof(char), typeof(TapAPIQuoteWhole) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] { typeof(uint), typeof(int), typeof(char), typeof(TapAPIContract) };
  private static global::System.Type[] swigMethodTypes7 = new global::System.Type[] { typeof(TapAPIQuoteWhole) };
}

}
