//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPIPositionProfit : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIPositionProfit(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIPositionProfit obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIPositionProfit obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIPositionProfit() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPIPositionProfit(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string PositionNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_PositionNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_PositionNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionStreamId {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_PositionStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_PositionStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double LMEPositionProfit {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_LMEPositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_LMEPositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionMarketValue {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_OptionMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_OptionMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CalculatePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_CalculatePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_CalculatePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double FloatingPL {
    set {
      EsunnyTapApiPINVOKE.TapAPIPositionProfit_FloatingPL_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIPositionProfit_FloatingPL_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIPositionProfit() : this(EsunnyTapApiPINVOKE.new_TapAPIPositionProfit__SWIG_0(), true) {
  }

  public TapAPIPositionProfit(TapAPIPositionProfit other) : this(EsunnyTapApiPINVOKE.new_TapAPIPositionProfit__SWIG_1(TapAPIPositionProfit.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
