//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPIOrderInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIOrderInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIOrderInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIOrderInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPIOrderInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char IsRiskOrder {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsRiskOrder_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsRiskOrder_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderSide_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_PositionEffect2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_PositionEffect2_get(swigCPtr);
      return ret;
    } 
  }

  public string InquiryNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_InquiryNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_InquiryNo_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public double StopPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_StopPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_StopPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMinQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMinQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMinQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderCanceledQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderCanceledQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderCanceledQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint MinClipSize {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MinClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MinClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxClipSize {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MaxClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MaxClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public string LicenseNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_LicenseNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_LicenseNo_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public string ParentAccountNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ParentAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ParentAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientOrderNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ClientOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ClientOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderLocalNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderLocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderLocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSystemNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderExchangeSystemNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderExchangeSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderExchangeSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderParentNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderParentNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderParentNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderParentSystemNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderParentSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderParentSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_TradeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_TradeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperChannelNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperSettleNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperSettleNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperSettleNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperUserNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertUserNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderInsertUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderInsertUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertTime {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderInsertTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderInsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderCommandUserNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderCommandUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderCommandUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderUpdateUserNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderUpdateUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderUpdateUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderUpdateTime {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderUpdateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderUpdateTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderState {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderState_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderMatchPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderMatchPrice2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMatchQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMatchQty2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderMatchQty2_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorText {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ErrorText_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ErrorText_get(swigCPtr);
      return ret;
    } 
  }

  public char IsBackInput {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsBackInput_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsBackInput_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDeleted {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsDeleted_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsDeleted_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderStreamID {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public uint UpperStreamID {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_UpperStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractSize2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_ContractSize2_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char FeeMode {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeMode_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeMode_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeParam {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeParam_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeParam_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char FeeMode2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeMode2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeMode2_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeParam2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeParam2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeParam2_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrencyGroup2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrencyGroup2_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrency2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeCurrency2_get(swigCPtr);
      return ret;
    } 
  }

  public char MarginMode {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginMode_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginMode_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginParam {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginParam_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginParam_get(swigCPtr);
      return ret;
    } 
  }

  public char MarginMode2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginMode2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginMode2_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginParam2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginParam2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginParam2_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_PreSettlePrice2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_PreSettlePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public uint OpenVol {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OpenVol_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OpenVol_get(swigCPtr);
      return ret;
    } 
  }

  public uint CoverVol {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CoverVol_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CoverVol_get(swigCPtr);
      return ret;
    } 
  }

  public uint OpenVol2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OpenVol2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OpenVol2_get(swigCPtr);
      return ret;
    } 
  }

  public uint CoverVol2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_CoverVol2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_CoverVol2_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeValue {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_FeeValue_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginValue {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarginValue_get(swigCPtr);
      return ret;
    } 
  }

  public char TacticsType {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_TacticsType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_TacticsType_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerCondition {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_TriggerCondition_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_TriggerCondition_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerPriceType {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_TriggerPriceType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_TriggerPriceType_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderQty2_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag2 {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_HedgeFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_HedgeFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public byte MarketLevel {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarketLevel_set(swigCPtr, value);
    } 
    get {
      byte ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_MarketLevel_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderDeleteByDisConnFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderDeleteByDisConnFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIOrderInfo_OrderDeleteByDisConnFlag_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderInfo() : this(EsunnyTapApiPINVOKE.new_TapAPIOrderInfo(), true) {
  }

}

}
