//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPICloseInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICloseInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICloseInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPICloseInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPICloseInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPICloseInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ParentAccountNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_ParentAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_ParentAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenOrderExchangeNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenOrderCommodityType {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenOrderCommodityNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseOrderExchangeNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseOrderCommodityType {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseOrderCommodityNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenMatchSource {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenMatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenMatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseMatchSource {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseMatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseMatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseSide {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseSide_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseSide_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseQty {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseQty_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_ClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_ClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenServerFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenOrderNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenExchangeMatchNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchDateTime {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseServerFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseOrderNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseExchangeMatchNo {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchDateTime {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseStreamId {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenCloseMode {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenCloseMode_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_OpenCloseMode_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumIncome {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_PremiumIncome_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_PremiumIncome_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumPay {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_PremiumPay_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_PremiumPay_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double UnExpProfit {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_UnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_UnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePL {
    set {
      EsunnyTapApiPINVOKE.TapAPICloseInfo_ClosePL_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPICloseInfo_ClosePL_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICloseInfo() : this(EsunnyTapApiPINVOKE.new_TapAPICloseInfo__SWIG_0(), true) {
  }

  public TapAPICloseInfo(TapAPICloseInfo other) : this(EsunnyTapApiPINVOKE.new_TapAPICloseInfo__SWIG_1(TapAPICloseInfo.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
