//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPICommodityOrderTimeInForceQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICommodityOrderTimeInForceQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICommodityOrderTimeInForceQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPICommodityOrderTimeInForceQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPICommodityOrderTimeInForceQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPICommodityOrderTimeInForceQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TapAPICommodity Commodity {
    set {
      EsunnyTapApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Commodity_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = EsunnyTapApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Commodity_get(swigCPtr);
      TapAPICommodity ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public int Count {
    set {
      EsunnyTapApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Count_set(swigCPtr, value);
    } 
    get {
      int ret = EsunnyTapApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Count_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderTimeInForces {
    set {
      EsunnyTapApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_OrderTimeInForces_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_OrderTimeInForces_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICommodityOrderTimeInForceQryRsp() : this(EsunnyTapApiPINVOKE.new_TapAPICommodityOrderTimeInForceQryRsp__SWIG_0(), true) {
  }

  public TapAPICommodityOrderTimeInForceQryRsp(TapAPICommodityOrderTimeInForceQryRsp other) : this(EsunnyTapApiPINVOKE.new_TapAPICommodityOrderTimeInForceQryRsp__SWIG_1(TapAPICommodityOrderTimeInForceQryRsp.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
