//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPINewOrder : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPINewOrder(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPINewOrder obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPINewOrder obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPINewOrder() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPINewOrder(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char IsRiskOrder {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_IsRiskOrder_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_IsRiskOrder_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderSide_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_PositionEffect2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_PositionEffect2_get(swigCPtr);
      return ret;
    } 
  }

  public string InquiryNo {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_InquiryNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_InquiryNo_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public double StopPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_StopPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPINewOrder_StopPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMinQty {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderMinQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderMinQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint MinClipSize {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_MinClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPINewOrder_MinClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxClipSize {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_MaxClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPINewOrder_MaxClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = EsunnyTapApiPINVOKE.TapAPINewOrder_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public char TacticsType {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_TacticsType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_TacticsType_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerCondition {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_TriggerCondition_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_TriggerCondition_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerPriceType {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_TriggerPriceType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_TriggerPriceType_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_OrderQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyTapApiPINVOKE.TapAPINewOrder_OrderQty2_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag2 {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_HedgeFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_HedgeFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public byte MarketLevel {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_MarketLevel_set(swigCPtr, value);
    } 
    get {
      byte ret = EsunnyTapApiPINVOKE.TapAPINewOrder_MarketLevel_get(swigCPtr);
      return ret;
    } 
  }

  public char FutureAutoCloseFlag {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_FutureAutoCloseFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPINewOrder_FutureAutoCloseFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperChannelNo {
    set {
      EsunnyTapApiPINVOKE.TapAPINewOrder_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPINewOrder_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPINewOrder() : this(EsunnyTapApiPINVOKE.new_TapAPINewOrder__SWIG_0(), true) {
  }

  public TapAPINewOrder(TapAPINewOrder other) : this(EsunnyTapApiPINVOKE.new_TapAPINewOrder__SWIG_1(TapAPINewOrder.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
