//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPIBillQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIBillQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIBillQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIBillQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIBillQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPIBillQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TapAPIBillQryReq Reqdata {
    set {
      EsunnyTapApiPINVOKE.TapAPIBillQryRsp_Reqdata_set(swigCPtr, TapAPIBillQryReq.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = EsunnyTapApiPINVOKE.TapAPIBillQryRsp_Reqdata_get(swigCPtr);
      TapAPIBillQryReq ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPIBillQryReq(cPtr, false);
      return ret;
    } 
  }

  public int BillLen {
    set {
      EsunnyTapApiPINVOKE.TapAPIBillQryRsp_BillLen_set(swigCPtr, value);
    } 
    get {
      int ret = EsunnyTapApiPINVOKE.TapAPIBillQryRsp_BillLen_get(swigCPtr);
      return ret;
    } 
  }

  public string BillText {
    set {
      EsunnyTapApiPINVOKE.TapAPIBillQryRsp_BillText_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIBillQryRsp_BillText_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIBillQryRsp() : this(EsunnyTapApiPINVOKE.new_TapAPIBillQryRsp__SWIG_0(), true) {
  }

  public TapAPIBillQryRsp(TapAPIBillQryRsp other) : this(EsunnyTapApiPINVOKE.new_TapAPIBillQryRsp__SWIG_1(TapAPIBillQryRsp.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
