//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyTap.Net {

public class TapAPIQuoteWhole : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIQuoteWhole(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIQuoteWhole obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIQuoteWhole obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIQuoteWhole() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyTapApiPINVOKE.delete_TapAPIQuoteWhole(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TapAPIContract Contract {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_Contract_set(swigCPtr, TapAPIContract.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_Contract_get(swigCPtr);
      TapAPIContract ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPIContract(cPtr, false);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public char TradingState {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_TradingState_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_TradingState_get(swigCPtr);
      return ret;
    } 
  }

  public string DateTimeStamp {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_DateTimeStamp_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_DateTimeStamp_get(swigCPtr);
      return ret;
    } 
  }

  public double QPreClosingPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPreClosingPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPreClosingPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QPreSettlePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QPrePositionQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPrePositionQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPrePositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QOpeningPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QOpeningPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QOpeningPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLastPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLastPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLastPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHighPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QHighPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QHighPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLowPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLowPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLowPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHisHighPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QHisHighPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QHisHighPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHisLowPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QHisLowPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QHisLowPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLimitUpPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLimitUpPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLimitUpPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLimitDownPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLimitDownPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLimitDownPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QTotalTurnover {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalTurnover_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalTurnover_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QPositionQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPositionQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QAveragePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QAveragePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QAveragePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QClosingPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QClosingPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QClosingPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QSettlePrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QLastQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLastQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QLastQty_get(swigCPtr);
      return ret;
    } 
  }

  public double[] QBidPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QBidPrice_set(swigCPtr, value);
    } 
    get {
      return EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QBidPrice_get(swigCPtr);
    } 
  }

  public ulong[] QBidQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QBidQty_set(swigCPtr, value);
    } 
    get {
      return EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QBidQty_get(swigCPtr);
    } 
  }

  public double[] QAskPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QAskPrice_set(swigCPtr, value);
    } 
    get {
      return EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QAskPrice_get(swigCPtr);
    } 
  }

  public ulong[] QAskQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QAskQty_set(swigCPtr, value);
    } 
    get {
      return EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QAskQty_get(swigCPtr);
    } 
  }

  public double QImpliedBidPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedBidPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedBidPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QImpliedBidQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedBidQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedBidQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QImpliedAskPrice {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedAskPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedAskPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QImpliedAskQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedAskQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QImpliedAskQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QPreDelta {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPreDelta_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPreDelta_get(swigCPtr);
      return ret;
    } 
  }

  public double QCurrDelta {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QCurrDelta_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QCurrDelta_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QInsideQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QInsideQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QInsideQty_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QOutsideQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QOutsideQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QOutsideQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QTurnoverRate {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTurnoverRate_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTurnoverRate_get(swigCPtr);
      return ret;
    } 
  }

  public ulong Q5DAvgQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_Q5DAvgQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_Q5DAvgQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QPERatio {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPERatio_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPERatio_get(swigCPtr);
      return ret;
    } 
  }

  public double QTotalValue {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalValue_get(swigCPtr);
      return ret;
    } 
  }

  public double QNegotiableValue {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QNegotiableValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QNegotiableValue_get(swigCPtr);
      return ret;
    } 
  }

  public long QPositionTrend {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPositionTrend_set(swigCPtr, value);
    } 
    get {
      long ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QPositionTrend_get(swigCPtr);
      return ret;
    } 
  }

  public double QChangeSpeed {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QChangeSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QChangeSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double QChangeRate {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QChangeRate_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QChangeRate_get(swigCPtr);
      return ret;
    } 
  }

  public double QChangeValue {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QChangeValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QChangeValue_get(swigCPtr);
      return ret;
    } 
  }

  public double QSwing {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QSwing_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QSwing_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalBidQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalBidQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalBidQty_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalAskQty {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalAskQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_QTotalAskQty_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIContract UnderlyContract {
    set {
      EsunnyTapApiPINVOKE.TapAPIQuoteWhole_UnderlyContract_set(swigCPtr, TapAPIContract.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = EsunnyTapApiPINVOKE.TapAPIQuoteWhole_UnderlyContract_get(swigCPtr);
      TapAPIContract ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPIContract(cPtr, false);
      return ret;
    } 
  }

  public TapAPIQuoteWhole() : this(EsunnyTapApiPINVOKE.new_TapAPIQuoteWhole__SWIG_0(), true) {
  }

  public TapAPIQuoteWhole(TapAPIQuoteWhole other) : this(EsunnyTapApiPINVOKE.new_TapAPIQuoteWhole__SWIG_1(TapAPIQuoteWhole.getCPtr(other)), true) {
    if (EsunnyTapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyTapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
